version: '3.7'

services:
  infoportal:
    build: .
    image: ${NAME}
    container_name: ${NAME}
    hostname: ${NAME}
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_RL_MAX_REQUESTS=${HTTP_RL_MAX_REQUESTS}
      - HTTP_RL_INTERVAL=${HTTP_RL_INTERVAL}
