version: '3.7'

services:
  infoportal:
    build: .
    image: ${NAME}
    container_name: ${NAME}
    hostname: ${NAME}
    restart: always
    ports:
      - "80:${HTTP_PORT}"
      - "443:${HTTPS_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_POOL_MAX_SIZE=${DB_POOL_MAX_SIZE}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - HTTP_RL_MAX_REQUESTS=${HTTP_RL_MAX_REQUESTS}
      - HTTP_RL_INTERVAL=${HTTP_RL_INTERVAL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/8e835d.online-server.cloud/
        target: /data
