version: '3.7'

services:
  infoportal:
    build: .
    image: ${NAME}
    container_name: ${NAME}
    hostname: ${NAME}
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
