# @hostname=info.regatta-hd.de
# @port=80
# @protocol=https
@hostname=localhost
@port=8080
@protocol=http
@baseUrl={{protocol}}://{{hostname}}:{{port}}

@activeRegatta=17

###
GET {{baseUrl}}/api/active_regatta HTTP/1.1
###
GET {{baseUrl}}/api/regattas HTTP/1.1
###
GET {{baseUrl}}/api/regattas/{{activeRegatta}}/athletes HTTP/1.1
###
GET {{baseUrl}}/api/regattas/{{activeRegatta}}/races HTTP/1.1
###
GET {{baseUrl}}/api/regattas/{{activeRegatta}}/heats HTTP/1.1
###
GET {{baseUrl}}/api/identity HTTP/1.1
###
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "password": ""
}
###
POST {{baseUrl}}/api/logout HTTP/1.1
###
GET {{baseUrl}}/api/identity HTTP/1.1
