name: Continuous Integration

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and test rust project
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          version: latest
          tags: tag:ci
          use-cache: 'true'

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Restore build & cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Enforce formatting
        run: cargo fmt --check

      - name: Linting
        run: cargo clippy -- -D warnings

      - name: Build and run tests
        uses: actions-rs/cargo@v1
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RUST_LOG: ${{ vars.RUST_LOG }}
        with:
          command: test
          args: --workspace

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --all-features
