name: Continuous Integration

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          version: 1.82.5
          tags: tag:ci

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore build & cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build and run tests
        uses: actions-rs/cargo@v1
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RUST_LOG: ${{ vars.RUST_LOG }}
        with:
          command: test
          args: --workspace

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --all-features
