name: Continuous Integration

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Caching
      - name: Cache Cargo directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ steps.toolchain.outputs.rustc }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-${{ steps.toolchain.outputs.rustc }}-

      - name: Build and run tests
        uses: actions-rs/cargo@v1
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          command: test
          args: --workspace

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --all-features
