name: Continuous Integration

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build and run tests
        uses: actions-rs/cargo@v1
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          command: test
          args: --workspace

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --all-features
